/**
 * Database type definitions for Supabase
 *
 * These types are automatically generated from your Supabase database schema.
 * DO NOT edit this file manually.
 *
 * To generate/update these types:
 * 1. Install Supabase CLI: npm install -g supabase
 * 2. Login to Supabase: npx supabase login
 * 3. Generate types:
 *    npx supabase gen types typescript --project-id <your-project-id> > src/lib/supabase/database.types.ts
 *
 * Alternative method using project reference:
 *    npx supabase gen types typescript --project-id <your-project-ref> --schema public > src/lib/supabase/database.types.ts
 *
 * You can find your project ID/ref in:
 * - Supabase Dashboard > Project Settings > General > Reference ID
 * - Or in your project URL: https://app.supabase.com/project/<project-ref>
 *
 * For more information:
 * https://supabase.com/docs/guides/api/rest/generating-types
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          username: string | null
          github_username: string | null
          level: number
          total_xp: number
          coding_xp: number
          learning_xp: number
          writing_xp: number
          health_xp: number
          github_xp: number
          current_streak: number
          longest_streak: number
          last_active_date: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          username?: string | null
          github_username?: string | null
          level?: number
          total_xp?: number
          coding_xp?: number
          learning_xp?: number
          writing_xp?: number
          health_xp?: number
          github_xp?: number
          current_streak?: number
          longest_streak?: number
          last_active_date?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          username?: string | null
          github_username?: string | null
          level?: number
          total_xp?: number
          coding_xp?: number
          learning_xp?: number
          writing_xp?: number
          health_xp?: number
          github_xp?: number
          current_streak?: number
          longest_streak?: number
          last_active_date?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      tasks: {
        Row: {
          id: string
          user_id: string
          title: string
          category: 'coding' | 'learning' | 'writing' | 'health'
          status: 'pending' | 'completed' | 'deleted'
          xp_reward: number
          completed_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          category: 'coding' | 'learning' | 'writing' | 'health'
          status?: 'pending' | 'completed' | 'deleted'
          xp_reward: number
          completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          category?: 'coding' | 'learning' | 'writing' | 'health'
          status?: 'pending' | 'completed' | 'deleted'
          xp_reward?: number
          completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'tasks_user_id_fkey'
            columns: ['user_id']
            referencedRelation: 'users'
            referencedColumns: ['id']
          }
        ]
      }
      xp_logs: {
        Row: {
          id: string
          user_id: string
          source_type: 'task' | 'github'
          source_id: string | null
          category: string
          xp_amount: number
          daily_total: number
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          source_type: 'task' | 'github'
          source_id?: string | null
          category: string
          xp_amount: number
          daily_total: number
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          source_type?: 'task' | 'github'
          source_id?: string | null
          category?: string
          xp_amount?: number
          daily_total?: number
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'xp_logs_user_id_fkey'
            columns: ['user_id']
            referencedRelation: 'users'
            referencedColumns: ['id']
          }
        ]
      }
      github_sync_logs: {
        Row: {
          id: string
          user_id: string
          sync_date: string
          commit_count: number
          xp_awarded: number
          synced_at: string
        }
        Insert: {
          id?: string
          user_id: string
          sync_date: string
          commit_count?: number
          xp_awarded?: number
          synced_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          sync_date?: string
          commit_count?: number
          xp_awarded?: number
          synced_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'github_sync_logs_user_id_fkey'
            columns: ['user_id']
            referencedRelation: 'users'
            referencedColumns: ['id']
          }
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_task_xp: {
        Args: {
          p_category: string
        }
        Returns: number
      }
      calculate_level: {
        Args: {
          p_total_xp: number
        }
        Returns: number
      }
      get_today_xp_total: {
        Args: {
          p_user_id: string
        }
        Returns: number
      }
      get_today_github_xp: {
        Args: {
          p_user_id: string
        }
        Returns: number
      }
      update_user_streak: {
        Args: {
          p_user_id: string
        }
        Returns: void
      }
      complete_task_with_xp: {
        Args: {
          p_task_id: string
          p_user_id: string
        }
        Returns: Json
      }
      award_github_xp: {
        Args: {
          p_user_id: string
          p_commit_count: number
          p_sync_date?: string
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type PublicSchema = Database[keyof Database]

export type Tables<
  PublicTableNameOrOptions extends
    | keyof (PublicSchema['Tables'] & PublicSchema['Views'])
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof (Database[PublicTableNameOrOptions['schema']]['Tables'] &
        Database[PublicTableNameOrOptions['schema']]['Views'])
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? (Database[PublicTableNameOrOptions['schema']]['Tables'] &
      Database[PublicTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : PublicTableNameOrOptions extends keyof (PublicSchema['Tables'] &
        PublicSchema['Views'])
    ? (PublicSchema['Tables'] &
        PublicSchema['Views'])[PublicTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  PublicTableNameOrOptions extends
    | keyof PublicSchema['Tables']
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions['schema']]['Tables']
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema['Tables']
    ? PublicSchema['Tables'][PublicTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  PublicTableNameOrOptions extends
    | keyof PublicSchema['Tables']
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions['schema']]['Tables']
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema['Tables']
    ? PublicSchema['Tables'][PublicTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  PublicEnumNameOrOptions extends
    | keyof PublicSchema['Enums']
    | { schema: keyof Database },
  EnumName extends PublicEnumNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = PublicEnumNameOrOptions extends { schema: keyof Database }
  ? Database[PublicEnumNameOrOptions['schema']]['Enums'][EnumName]
  : PublicEnumNameOrOptions extends keyof PublicSchema['Enums']
    ? PublicSchema['Enums'][PublicEnumNameOrOptions]
    : never
